---
- name: Skapa användare på host
  hosts: all
  become: true
  vars:
    user: user54321
    userstate: present
  tasks:
    - name: Skapa användare {{ user }}
      user:
        name: "{{ user }}"
        state: "{{ userstate }}"