version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:40

dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.0
    # package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner==2.4.0
    # package_pip: ansible-runner
  system:
  - python3-dns
  galaxy:
    collections:
    - name: community.general
