- name: Test ee
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    lookup_host: "google.se"
  tasks:
    - name: dig google.se
      debug:
        msg: "{{ lookup('community.general.dig', '{{ lookup_host }}')}}"